import './globals.css';
import Html from '@components/Layout/Html';
import Header from '@components/Layout/Header';
import Main from '@components/Layout/Main';
import Body from '@components/Layout/Body';
import Footer from '@components/Layout/Footer';
import dynamic from 'next/dynamic';

const BreadCrumb = dynamic(() => import('@components/BreadCrumb'), { ssr: false });

export const metadata = {
    title: 'Meninas Cambados',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }: Children) => {
    return (
        <Html>
            <Body>
                <Header />
                <Main>
                    <div style={{ position: 'relative' }}>
                        <BreadCrumb />
                        {children}
                    </div>
                </Main>
                <Footer />
            </Body>
        </Html>
    );
};

export default RootLayout;
