import './globals.css';
import Header from '@components/Header';
import Footer from '@components/Footer';
import styles from './layout.module.css';
import { Breadcrumb } from '@/components/BreadCrumb';
import { Karla } from 'next/font/google';

export const karla = Karla({
    weight: ['200', '400', '700'],
    style: 'normal',
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-karla',
});

export const metadata = {
    title: 'Meninas Cambados',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="es" className={`${karla.variable}`}>
            <body className={styles.body}>
                <Header />
                <main className={styles.main}>
                    <div style={{ position: 'relative' }}>
                        <Breadcrumb />
                        {children}
                    </div>
                </main>
                <Footer />
            </body>
        </html>
    );
}
